### ISSUE TITLE
broken broadcasts

### ISSUE THREAD

**Issue by gre4kapi** [snoodledev/themast#6]
### Describe the bug

all broadcasts are a random set of letters and numbers. Is this how it should be? Could this be due to the fact that I have Russian in the game? If it's because of the language, then how can I read the broadcasts again? I'll attach a screenshot when I find another broadcast token

### Do you have the Downpour DLC enabled?

- [X] DLC enabled

### Attach logs

[consoleLog.txt](https://github.com/snoodledev/themast/files/14388152/consoleLog.txt)
[LogOutput.log](https://github.com/snoodledev/themast/files/14388156/LogOutput.log)
[crsLog.txt](https://github.com/snoodledev/themast/files/14388164/crsLog.txt)
no exception log

### Attach Screenshots

Will attach when find new broadcast token in-game
UPD:
![Screenshot_4](https://github.com/snoodledev/themast/assets/87585054/de14923e-f90d-4231-aaef-afecab1efce6)
![Screenshot_2](https://github.com/snoodledev/themast/assets/87585054/4d6a5cb6-f412-41fb-87c8-257ed49af9f7)
![Screenshot_3](https://github.com/snoodledev/themast/assets/87585054/a76181bb-3a0e-47a9-a0bb-f42b61bb7b09)

**Comment by gre4kapi** [comment]
UPD: Guys, you forgot to translate the broadcasts; in the localization files, all broadcasts have the same text.
Example: 
![Screenshot_5](https://github.com/snoodledev/themast/assets/87585054/93933780-1467-400c-a333-fb610cfefe8b)
![Screenshot_6](https://github.com/snoodledev/themast/assets/87585054/3fad2058-6317-4773-a0a7-351b3ca625ca)

**Comment by snoodledev** [comment]
The translations all being the same language is intended, I haven't gotten proper translations done yet - the copies are just to avoid glitchy behaviour.
The glitched text is definitely not intended however - I believe the files were encrypted incorrectly, going to look into fixing this 👍

**Comment by snoodledev** [comment]
This should be fixed in the latest version!
