### ISSUE TITLE
lb-fgf-m4-ik.hvfly-tm

### ISSUE THREAD

**Issue by Nurseit05** [snoodledev/themast#9]
### Describe the bug

Hello, I have installed all three dependencies crs, regionkit and fisobs but I can't get into remix to install anything else but I can't figure it out.

### Do you have the Downpour DLC enabled?

- [X] DLC enabled

### Attach logs

I have rain world torrenting

### Attach Screenshots

![Снимок экрана 2024-07-27 111141](https://github.com/user-attachments/assets/4f624cc8-8057-4745-8f43-cef0f77f4aae)

**Comment by snoodledev** [comment]
Hi, seems like you're missing one of the dependency mods, Hoverfly - this was added in a recent update so you might have missed it. I'd double-check the workshop page to make sure you're subscribed to all the dependencies 👍
